// AUTO-GENERATED by scripts/youtube/match-videos-to-posts.js — do not hand-edit.
// Maps a blog post slug to the channel's own gameplay video (first-hand media / E-E-A-T).
// Rendered as an embedded player + VideoObject JSON-LD on the post.
export type PostVideo = { id: string; title: string };
export const VIDEO_MAP: Record<string, PostVideo> = {
  "dark-enchantress-cookie-toppings-build": {
    "id": "DkG_afMpjyY",
    "title": "Dark Enchantress Cookie Gear Guide | Cookie Run Kingdom"
  },
  "eternal-sugar-cookie-toppings-build": {
    "id": "JeLyNsZ3mSI",
    "title": "Eternal Sugar Cookie Gear Guide | Cookie Run Kingdom"
  },
  "sea-fairy-cookie-toppings-build": {
    "id": "doDl71tioXw",
    "title": "Sea Fairy Cookie Gear Guide | Cookie Run Kingdom"
  },
  "silent-salt-cookie-toppings-build": {
    "id": "MMG9viVIzGo",
    "title": "Silent Salt Cookie Build | Best Gear & Toppings Guide"
  },
  "wind-archer-cookie-toppings-build": {
    "id": "DLI6Up__o-0",
    "title": "Wind Archer Cookie Gear Guide | Cookie Run Kingdom"
  }
};
