// AUTO-GENERATED by scripts/youtube/match-videos-to-posts.js — do not hand-edit.
// Maps a blog post slug to the channel's own gameplay video (first-hand media / E-E-A-T).
// Rendered as an embedded player + VideoObject JSON-LD on the post.
// uploadDate is optional: backfill it (1 cheap videos.list call) to make the VideoObject
// rich-result eligible; absent is still valid structured data.
export type PostVideo = { id: string; title: string; uploadDate?: string };
export const VIDEO_MAP: Record<string, PostVideo> = {
  "black-pearl-cookie-toppings-build": {
    "id": "YMMjl07QzY4",
    "title": "Black Pearl Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "burning-spice-cookie-toppings-build": {
    "id": "JwdN8MLjdL8",
    "title": "Burning Spice Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "candy-apple-cookie-toppings-build": {
    "id": "PTeepPjK9bQ",
    "title": "Candy Apple Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "capsaicin-cookie-toppings-build": {
    "id": "cEgVZWpO3uw",
    "title": "Capsaicin Cookie Toppings | BURN TIP! | Topping Guide | Best Toppings | Cookie Run Kingdom"
  },
  "clotted-cream-cookie-toppings-build": {
    "id": "oMSpF4Sj2BQ",
    "title": "Clotted Cream Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "cookie-run-kingdom-tier-list": {
    "id": "2TNyU52Ybeo",
    "title": "Tier List Error Busters Season 2"
  },
  "crunchy-chip-cookie-toppings-build": {
    "id": "_T0P0JmvARA",
    "title": "Crunchy Chip Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "dark-cacao-cookie-toppings-build": {
    "id": "DJX44ZBn0jg",
    "title": "Dark Cacao Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "dark-enchantress-cookie-toppings-build": {
    "id": "DkG_afMpjyY",
    "title": "Dark Enchantress Cookie Gear Guide | Cookie Run Kingdom"
  },
  "elder-faerie-cookie-toppings-build": {
    "id": "zFZpDm3-6XM",
    "title": "Elder Faerie Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "eternal-sugar-cookie-toppings-build": {
    "id": "JeLyNsZ3mSI",
    "title": "Eternal Sugar Cookie Gear Guide | Cookie Run Kingdom"
  },
  "frost-queen-cookie-toppings-build": {
    "id": "qp-t6dvJnZ8",
    "title": "Frost Queen Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "golden-cheese-cookie-toppings-build": {
    "id": "8UDZgl7Ng7E",
    "title": "Awakened Golden Cheese Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "hollyberry-cookie-toppings-build": {
    "id": "rB5wqOWBVLw",
    "title": "Awakened Hollyberry Aegis Cookie Gear Guide | Cookie Run Kingdom"
  },
  "mystic-flour-cookie-toppings-build": {
    "id": "FmwvLSl1lqg",
    "title": "Mystic Flour Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "pure-vanilla-awakened-toppings": {
    "id": "Y_4RUnbOGj0",
    "title": "Awakened Pure Vanilla Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "sea-fairy-cookie-toppings-build": {
    "id": "doDl71tioXw",
    "title": "Sea Fairy Cookie Gear Guide | Cookie Run Kingdom"
  },
  "shadow-milk-cookie-toppings-build": {
    "id": "d1WIE_lwmEs",
    "title": "Shadow Milk Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "silent-salt-cookie-toppings-build": {
    "id": "MMG9viVIzGo",
    "title": "Silent Salt Cookie Build | Best Gear & Toppings Guide"
  },
  "star-coral-cookie-toppings-build": {
    "id": "4Mp_Ox8IOQQ",
    "title": "Star Coral Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "stormbringer-cookie-toppings-build": {
    "id": "4F9OMzybr2A",
    "title": "Stormbringer Cookie Beascuit & Topping Guide | Cookie Run Kingdom"
  },
  "twizzly-gummy-cookie-toppings-build": {
    "id": "em-C2UZjeoI",
    "title": "Twizzly Gummy Cookie Toppings |Topping Guide | Best Toppings | Cookie Run Kingdom"
  },
  "white-lily-cookie-toppings-build": {
    "id": "niy0puWNkdI",
    "title": "Awakened White Lily Cookie Gear Guide | Cookie Run Kingdom"
  },
  "wind-archer-cookie-toppings-build": {
    "id": "DLI6Up__o-0",
    "title": "Wind Archer Cookie Gear Guide | Cookie Run Kingdom"
  }
};
