// AUTO-GENERATED by scripts/youtube/match-videos-to-posts.js — do not hand-edit.
// Maps a blog post slug to the channel's own gameplay video (first-hand media / E-E-A-T).
// Rendered as an embedded player + VideoObject JSON-LD on the post.
// uploadDate is optional: backfill it (1 cheap videos.list call) to make the VideoObject
// rich-result eligible; absent is still valid structured data.
export type PostVideo = { id: string; title: string; uploadDate?: string };
export const VIDEO_MAP: Record<string, PostVideo> = {
  "black-lemonade-cookie-toppings-build": {
    "id": "2g_QiK6pvzY",
    "title": "Black Lemonade Cookie | DAMAGE TIP | Topping Guide | Best Toppings | Cookie Run Kingdom",
    "uploadDate": "2023-07-22"
  },
  "black-pearl-cookie-toppings-build": {
    "id": "YMMjl07QzY4",
    "title": "Black Pearl Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-04-30"
  },
  "burning-spice-cookie-toppings-build": {
    "id": "JwdN8MLjdL8",
    "title": "Burning Spice Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-10-26"
  },
  "camellia-cookie-toppings-build": {
    "id": "Wh4AufHizxU",
    "title": "Camellia Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-11-28"
  },
  "candy-apple-cookie-toppings-build": {
    "id": "PTeepPjK9bQ",
    "title": "Candy Apple Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2025-01-15"
  },
  "capsaicin-cookie-toppings-build": {
    "id": "cEgVZWpO3uw",
    "title": "Capsaicin Cookie Toppings | BURN TIP! | Topping Guide | Best Toppings | Cookie Run Kingdom",
    "uploadDate": "2023-04-12"
  },
  "caramel-arrow-cookie-toppings-build": {
    "id": "l2w5uS-fOQ4",
    "title": "Caramel Arrow Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-06-08"
  },
  "clotted-cream-cookie-toppings-build": {
    "id": "oMSpF4Sj2BQ",
    "title": "Clotted Cream Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-05-01"
  },
  "cookie-run-kingdom-tier-list": {
    "id": "2TNyU52Ybeo",
    "title": "Tier List Error Busters Season 2",
    "uploadDate": "2024-08-04"
  },
  "cotton-cookie-toppings-build": {
    "id": "fqs6F-t6pwk",
    "title": "Cotton Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-01-27"
  },
  "crimson-coral-cookie-toppings-build": {
    "id": "WxLVoBFx1Rw",
    "title": "Crimson Coral Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-02-24"
  },
  "crunchy-chip-cookie-toppings-build": {
    "id": "_T0P0JmvARA",
    "title": "Crunchy Chip Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-06-21"
  },
  "dark-cacao-cookie-toppings-build": {
    "id": "DJX44ZBn0jg",
    "title": "Dark Cacao Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-04-04"
  },
  "dark-enchantress-cookie-toppings-build": {
    "id": "DkG_afMpjyY",
    "title": "Dark Enchantress Cookie Gear Guide | Cookie Run Kingdom",
    "uploadDate": "2026-01-14"
  },
  "elder-faerie-cookie-toppings-build": {
    "id": "zFZpDm3-6XM",
    "title": "Elder Faerie Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-03-16"
  },
  "eternal-sugar-cookie-toppings-build": {
    "id": "JeLyNsZ3mSI",
    "title": "Eternal Sugar Cookie Gear Guide | Cookie Run Kingdom",
    "uploadDate": "2025-06-06"
  },
  "financier-cookie-toppings-build": {
    "id": "-NVdCBwdol8",
    "title": "Financier Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-05-15"
  },
  "frost-queen-cookie-toppings-build": {
    "id": "qp-t6dvJnZ8",
    "title": "Frost Queen Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-02-23"
  },
  "golden-cheese-cookie-toppings-build": {
    "id": "8UDZgl7Ng7E",
    "title": "Awakened Golden Cheese Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-11-05"
  },
  "hollyberry-cookie-toppings-build": {
    "id": "rB5wqOWBVLw",
    "title": "Awakened Hollyberry Aegis Cookie Gear Guide | Cookie Run Kingdom",
    "uploadDate": "2025-06-21"
  },
  "mercurial-knight-cookie-toppings-build": {
    "id": "d2U-5lw7zVI",
    "title": "Mercurial Knight Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-02-07"
  },
  "moonlight-cookie-toppings-build": {
    "id": "OVL_Sja-FNM",
    "title": "Moonlight Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-03-11"
  },
  "mystic-flour-cookie-toppings-build": {
    "id": "FmwvLSl1lqg",
    "title": "Mystic Flour Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-06-01"
  },
  "oyster-cookie-toppings-build": {
    "id": "uQbk1T4LR7k",
    "title": "Oyster Cookie Toppings | Topping Guide | Best Toppings | Cookie Run Kingdom",
    "uploadDate": "2022-07-02"
  },
  "peppermint-cookie-toppings-build": {
    "id": "6zJOpaKAMvQ",
    "title": "Peppermint Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-10-17"
  },
  "pure-vanilla-awakened-toppings": {
    "id": "Y_4RUnbOGj0",
    "title": "Awakened Pure Vanilla Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2025-03-03"
  },
  "sea-fairy-cookie-toppings-build": {
    "id": "doDl71tioXw",
    "title": "Sea Fairy Cookie Gear Guide | Cookie Run Kingdom",
    "uploadDate": "2025-08-28"
  },
  "shadow-milk-cookie-toppings-build": {
    "id": "d1WIE_lwmEs",
    "title": "Shadow Milk Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2025-02-07"
  },
  "sherbet-cookie-toppings-build": {
    "id": "zNXcYKHJ3bY",
    "title": "Sherbet Cookie Toppings | Topping Guide | Best Toppings | Cookie Run Kingdom",
    "uploadDate": "2023-01-08"
  },
  "silent-salt-cookie-toppings-build": {
    "id": "MMG9viVIzGo",
    "title": "Silent Salt Cookie Build | Best Gear & Toppings Guide",
    "uploadDate": "2025-09-25"
  },
  "smoked-cheese-cookie-toppings-build": {
    "id": "foIqEo89g90",
    "title": "Smoked Cheese Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-10-30"
  },
  "star-coral-cookie-toppings-build": {
    "id": "4Mp_Ox8IOQQ",
    "title": "Star Coral Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-08-15"
  },
  "stormbringer-cookie-toppings-build": {
    "id": "4F9OMzybr2A",
    "title": "Stormbringer Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-05-03"
  },
  "tea-knight-cookie-toppings-build": {
    "id": "A-j-ad92Sz4",
    "title": "Tea Knight Cookie Toppings | Topping Guide | Best Toppings | Cookie Run Kingdom",
    "uploadDate": "2022-02-08"
  },
  "twizzly-gummy-cookie-toppings-build": {
    "id": "em-C2UZjeoI",
    "title": "Twizzly Gummy Cookie Toppings |Topping Guide | Best Toppings | Cookie Run Kingdom",
    "uploadDate": "2022-06-29"
  },
  "white-lily-cookie-toppings-build": {
    "id": "niy0puWNkdI",
    "title": "Awakened White Lily Cookie Gear Guide | Cookie Run Kingdom",
    "uploadDate": "2025-11-16"
  },
  "wildberry-cookie-toppings-build": {
    "id": "v-W2amna6NI",
    "title": "Wildberry Cookie Beascuit & Topping Guide | Cookie Run Kingdom",
    "uploadDate": "2024-11-26"
  },
  "wind-archer-cookie-toppings-build": {
    "id": "DLI6Up__o-0",
    "title": "Wind Archer Cookie Gear Guide | Cookie Run Kingdom",
    "uploadDate": "2025-12-24"
  }
};
